/*
**  ClanLib SDK
**  Copyright (c) 1997-2009 The ClanLib Team
**
**  This software is provided 'as-is', without any express or implied
**  warranty.  In no event will the authors be held liable for any damages
**  arising from the use of this software.
**
**  Permission is granted to anyone to use this software for any purpose,
**  including commercial applications, and to alter it and redistribute it
**  freely, subject to the following restrictions:
**
**  1. The origin of this software must not be misrepresented; you must not
**     claim that you wrote the original software. If you use this software
**     in a product, an acknowledgment in the product documentation would be
**     appreciated but is not required.
**  2. Altered source versions must be plainly marked as such, and must not be
**     misrepresented as being the original software.
**  3. This notice may not be removed or altered from any source distribution.
**
**  Note: Some of the libraries ClanLib may link to may have additional
**  requirements or restrictions.
**
**  File Author(s):
**
**    Harry Storbacka
*/

#include "precomp.h"
#include "callback_info.h"

CallbackInfo::CallbackInfo()
{
	populate();	
}


void CallbackInfo::populate()
{
	// The following was generated by copy-pasting the results of Visual C++ 7.1 find
	// in files for "func_" to callbacks.txt, and removing callbacks not belonging to
	// components. The python script gui_callbacks_listing_to_code.py finally produces what you see here.

	callbacks.push_back(CallbackData(cl_text("gui_component"), cl_text("render"), cl_text("CL_GraphicContext &"), cl_text(" const CL_Rect &")));
	callbacks.push_back(CallbackData(cl_text("gui_component"), cl_text("process_message"), cl_text("CL_GUIMessage &"), cl_text("")));
	callbacks.push_back(CallbackData(cl_text("gui_component"), cl_text("style_changed"), cl_text(""), cl_text("")));
	callbacks.push_back(CallbackData(cl_text("gui_component"), cl_text("enablemode_changed"), cl_text(""), cl_text("")));
	callbacks.push_back(CallbackData(cl_text("gui_component"), cl_text("resized"), cl_text(""), cl_text("")));
	callbacks.push_back(CallbackData(cl_text("gui_component"), cl_text("constrain_resize"), cl_text("CL_Rect &"), cl_text("")));
	callbacks.push_back(CallbackData(cl_text("gui_component"), cl_text("create_custom_component"), cl_text(""), cl_text("")));
	callbacks.push_back(CallbackData(cl_text("checkbox"), cl_text("checked"), cl_text(""), cl_text("")));
	callbacks.push_back(CallbackData(cl_text("checkbox"), cl_text("unchecked"), cl_text(""), cl_text("")));
	callbacks.push_back(CallbackData(cl_text("checkbox"), cl_text("indeterminated"), cl_text(""), cl_text("")));
	callbacks.push_back(CallbackData(cl_text("checkbox"), cl_text("state_changed"), cl_text(""), cl_text("")));
	callbacks.push_back(CallbackData(cl_text("combobox"), cl_text("dropdown_opened"), cl_text(""), cl_text("")));
	callbacks.push_back(CallbackData(cl_text("combobox"), cl_text("dropdown_closed"), cl_text(""), cl_text("")));
	callbacks.push_back(CallbackData(cl_text("combobox"), cl_text("before_edit_changed"), cl_text(""), cl_text("")));
	callbacks.push_back(CallbackData(cl_text("combobox"), cl_text("after_edit_changed"), cl_text(""), cl_text("")));
	callbacks.push_back(CallbackData(cl_text("combobox"), cl_text("lineedit_unhandled_event"), cl_text("CL_InputEvent"), cl_text("")));
	callbacks.push_back(CallbackData(cl_text("combobox"), cl_text("display_popup"), cl_text("CL_Rect"), cl_text("")));
	callbacks.push_back(CallbackData(cl_text("combobox"), cl_text("item_selected"), cl_text("int"), cl_text("")));
	callbacks.push_back(CallbackData(cl_text("combobox"), cl_text("selection_changed"), cl_text("int"), cl_text("")));
	callbacks.push_back(CallbackData(cl_text("lineedit"), cl_text("before_edit_changed"), cl_text("CL_InputEvent"), cl_text("")));
	callbacks.push_back(CallbackData(cl_text("lineedit"), cl_text("after_edit_changed"), cl_text("CL_InputEvent"), cl_text("")));
	callbacks.push_back(CallbackData(cl_text("lineedit"), cl_text("selection_changed"), cl_text(""), cl_text("")));
	callbacks.push_back(CallbackData(cl_text("lineedit"), cl_text("focus_gained"), cl_text(""), cl_text("")));
	callbacks.push_back(CallbackData(cl_text("lineedit"), cl_text("unhandled_event"), cl_text("CL_InputEvent"), cl_text("")));
	callbacks.push_back(CallbackData(cl_text("listview"), cl_text("selection_changed"), cl_text("CL_ListViewSelection"), cl_text("")));
	callbacks.push_back(CallbackData(cl_text("listview"), cl_text("item_edited"), cl_text("CL_ListViewItem"), cl_text("")));
	callbacks.push_back(CallbackData(cl_text("listview"), cl_text("key_pressed"), cl_text("CL_InputEvent"), cl_text("")));
	callbacks.push_back(CallbackData(cl_text("listview"), cl_text("key_released"), cl_text("CL_InputEvent"), cl_text("")));
	callbacks.push_back(CallbackData(cl_text("push_button"), cl_text("clicked"), cl_text(""), cl_text("")));
	callbacks.push_back(CallbackData(cl_text("radiobutton"), cl_text("selected"), cl_text(""), cl_text("")));
	callbacks.push_back(CallbackData(cl_text("radiobutton"), cl_text("unselected"), cl_text(""), cl_text("")));
	callbacks.push_back(CallbackData(cl_text("radiobutton"), cl_text("group_selection_changed"), cl_text("CL_RadioButton*"), cl_text("")));
	callbacks.push_back(CallbackData(cl_text("scrollbar"), cl_text("scroll"), cl_text(""), cl_text("")));
	callbacks.push_back(CallbackData(cl_text("scrollbar"), cl_text("scroll_min"), cl_text(""), cl_text("")));
	callbacks.push_back(CallbackData(cl_text("scrollbar"), cl_text("scroll_max"), cl_text(""), cl_text("")));
	callbacks.push_back(CallbackData(cl_text("scrollbar"), cl_text("scroll_line_decrement"), cl_text(""), cl_text("")));
	callbacks.push_back(CallbackData(cl_text("scrollbar"), cl_text("scroll_line_increment"), cl_text(""), cl_text("")));
	callbacks.push_back(CallbackData(cl_text("scrollbar"), cl_text("scroll_page_decrement"), cl_text(""), cl_text("")));
	callbacks.push_back(CallbackData(cl_text("scrollbar"), cl_text("scroll_page_increment"), cl_text(""), cl_text("")));
	callbacks.push_back(CallbackData(cl_text("scrollbar"), cl_text("scroll_thumb_position"), cl_text(""), cl_text("")));
	callbacks.push_back(CallbackData(cl_text("scrollbar"), cl_text("scroll_thumb_track"), cl_text(""), cl_text("")));
	callbacks.push_back(CallbackData(cl_text("scrollbar"), cl_text("scroll_end"), cl_text(""), cl_text("")));
	callbacks.push_back(CallbackData(cl_text("slider"), cl_text("slider_value_changed"), cl_text(""), cl_text("")));
	callbacks.push_back(CallbackData(cl_text("slider"), cl_text("slider_decremented"), cl_text(""), cl_text("")));
	callbacks.push_back(CallbackData(cl_text("slider"), cl_text("slider_incremented"), cl_text(""), cl_text("")));
	callbacks.push_back(CallbackData(cl_text("slider"), cl_text("slider_moved"), cl_text(""), cl_text("")));
	callbacks.push_back(CallbackData(cl_text("spin"), cl_text("value_changed"), cl_text(""), cl_text("")));
	callbacks.push_back(CallbackData(cl_text("statusbar"), cl_text("part_double_clicked"), cl_text(""), cl_text("")));
	callbacks.push_back(CallbackData(cl_text("toolbar"), cl_text("item_clicked"), cl_text("CL_ToolBarItem"), cl_text("")));
	callbacks.push_back(CallbackData(cl_text("toolbar"), cl_text("item_selected"), cl_text("CL_ToolBarItem"), cl_text("")));
	callbacks.push_back(CallbackData(cl_text("toolbar"), cl_text("item_unselected"), cl_text("CL_ToolBarItem"), cl_text("")));
	callbacks.push_back(CallbackData(cl_text("window"), cl_text("close"), cl_text(""), cl_text("")));
	callbacks.push_back(CallbackData(cl_text("window"), cl_text("resize"), cl_text("CL_Rect&"), cl_text("")));
}

std::vector<CallbackData> CallbackInfo::get_callbacks( const CL_StringRef &comp_type )
{
	std::vector<CallbackData> retval;
	std::vector<CallbackData>::iterator it;
	for (it = callbacks.begin(); it != callbacks.end(); ++it)
	{
		if ((*it).get_component_type() == comp_type)
		{
			retval.push_back((*it));
		}
	}
	return retval;
}
