EXAMPLE_BIN=chess3d
OBJF = \
./3D/orientation.o \
./3D/position.o \
./3D/camera.o \
./3D/lib3ds_help.o \
./model.o \
./program.o \
./precomp.o \
./skybox.o

LIBS=clanApp clanDisplay clanCore clanGL
EXTRA_LIBS=-l3ds

CXXFLAGS += -I./ -I3D

include ../Makefile.conf

# EOF #

