EXAMPLE_BIN=font
OBJF = ./Sources/font.o \
./Sources/precomp.o \
./Sources/settings.o

LIBS=clanApp clanDisplay clanCore clanGL clanUI
CXXFLAGS += -I Sources -I ./

include ../../Makefile.conf

# EOF #
