EXAMPLE_BIN=webbrowser
SOURCE = $(wildcard *.cpp)
OBJF = $(patsubst %.cpp,%.o,$(SOURCE))


CXXFLAGS=-lgif
LIBS=clanCore clanApp clanGL clanSound clanDisplay clanCSSLayout clanGUI clanNetwork clanDatabase clanSqlite

include ../../Makefile.conf
