VPATH = ZZ_Theme:MenuSystem
EXAMPLE_BIN=guistyle
OBJF = NS_MenuGeneric.o \
NS_MenuManager.o \
NS_Menu_Credits.o \
NS_Menu_Game.o \
NS_Menu_Main.o \
NS_Menu_Play.o \
NS_MessageBox.o \
NS_Profile.o \
button_zz.o \
checkbox_zz.o \
frame_zz.o \
inputbox_zz.o \
label_zz.o \
listbox_zz.o \
scrollbar_zz.o \
stylemanager_zz.o \
window_zz.o \
main.o

LIBS=clanApp clanDisplay clanCore clanGL clanGUI

include ../Makefile.conf

# EOF #
