EXAMPLE_BIN= glyphbuffertest

include ../Makefile.conf

glyphbuffertest: Intermediate/glyphbuffertest.o
	$(CXX) -g3 $(COMP_OPTIONS) Intermediate/glyphbuffertest.o -o glyphbuffertest -lclanApp -lclanDisplay -lclanGL -lclanCore
