EXAMPLE_BIN=instancing
OBJF = ./Sources/shader_color.o \
./Sources/model.o \
./Sources/example.o \
./Sources/shader_texture.o \
./Sources/graphic_store.o \
./Sources/program.o \
./Sources/scene_object.o \
./Sources/scene.o \
./Sources/precomp.o \
./Sources/instanced_object.o \
./Sources/shader_color_instanced.o

LIBS=clanApp clanDisplay clanCore clanGL

CXXFLAGS += -I./ -I Sources
EXTRA_LIBS=-lassimp

include ../../Makefile.conf

# EOF #

