EXAMPLE_BIN=texturepacker

OBJF= \
./Sources/view.o \
./Sources/sprite_component.o \
./Sources/application.o \
./Sources/texture_packer.o \
./Sources/view_workspace.o \
./Sources/main_window.o \
./Sources/texturegroup_component.o \
./Sources/precomp.o \
./Sources/Views/resource_viewer_view.o \
./Sources/Views/ico_creator_view.o \
./Sources/Views/texture_packer_view.o \
./Sources/Views/welcome_view.o \
./Sources/Views/css_packer_view.o \
./Sources/Dialogs/create_collision_data_dialog.o \
./Sources/css_packer.o

LIBS=clanCore clanApp clanDisplay clanGUI clanGL

CXXFLAGS += -I./Sources -I./Sources/Views

include ../../Examples/Makefile.conf

# EOF #
