EXAMPLE_BIN=texturepacker

OBJF= \
Sources/application.o \
Sources/main_window.o \
Sources/precomp.o \
Sources/sprite_component.o \
Sources/texturegroup_component.o \
Sources/texture_packer.o

LIBS=clanCore clanApp clanDisplay clanGUI clanGL

include ../../Examples/Makefile.conf

# EOF #
