EXAMPLE_BIN=basic2d
OBJF = Sources/basic2d.o Sources/precomp.o Sources/program.o
LIBS=clanApp clanDisplay clanCore clanGL
#LIBS=clanApp clanDisplay clanCore clanGL1

include ../../Makefile.conf

# EOF #

