EXAMPLE_BIN=roadgeddon
SOURCE := $(wildcard Source/*.cpp)
OBJF := $(patsubst %.cpp,%.o,$(SOURCE))

LIBS=clanCore clanDisplay clanApp clanGL clanSWRender clanSound clanPhysics2D

include ../../Makefile.conf

# EOF #
