EXAMPLE_BIN=sound
OBJF = Sources/app.o Sources/program.o Sources/gui.o
LIBS=clanApp clanDisplay clanCore clanSWRender clanGL clanGL1 clanGUI clanSound clanVorbis clanMikMod

include ../../Makefile.conf

# EOF #

