EXAMPLE_BIN=particle
OBJF = Sources/LinearParticle/L_MotionController.o \
Sources/LinearParticle/L_EffectManager.o \
Sources/LinearParticle/L_ParticleEffect.o \
Sources/LinearParticle/L_EffectEmitter.o \
Sources/LinearParticle/L_ExplosionEffect.o \
Sources/LinearParticle/L_ShootingEffect.o \
Sources/LinearParticle/L_Particle.o \
Sources/LinearParticle/L_DroppingEffect.o \
Sources/LinearParticle/L_Vector.o \
Sources/LinearParticle/L_ParticleSystem.o \
Sources/LinearParticle/L_ParticleMem.o \
Sources/Demos/circle.o \
Sources/Demos/cmotion.o \
Sources/Demos/circle2.o \
Sources/Demos/framerate_counter.o \
Sources/Demos/usercollision.o \
Sources/Demos/shooting.o \
Sources/Demos/msmall.o \
Sources/Demos/simple.o \
Sources/Demos/explosion.o \
Sources/particle.o \
Sources/program.o \
Sources/precomp.o

LIBS=clanApp clanDisplay clanCore clanGL

CXXFLAGS += -I./ -I../ -I Sources

include ../../Makefile.conf

# EOF #

