EXAMPLE_BIN=input
OBJF = ./Sources/app.o \
./Sources/text_shooter.o \
./Sources/program.o \
./Sources/precomp.o

LIBS=clanApp clanDisplay clanCore clanSWRender clanGL clanGL1

include ../../Makefile.conf

# EOF #

