EXAMPLE_BIN=gui3d
OBJF =  Sources/app.o \
 Sources/panel.o \
 Sources/slider.o \
 Sources/program.o \
 Sources/gui.o \
 Sources/window_1.o \
 Sources/precomp.o \
 Sources/component3d.o

LIBS=clanApp clanDisplay clanCore clanSWRender clanGL clanGL1 clanGUI

include ../../Makefile.conf

# EOF #

