EXAMPLE_BIN=quaternion
OBJF = ./Sources/options.o \
./Sources/shader_color.o \
./Sources/model.o \
./Sources/example.o \
./Sources/graphic_store.o \
./Sources/program.o \
./Sources/scene_object.o \
./Sources/scene.o \
./Sources/precomp.o

LIBS=clanApp clanDisplay clanCore clanGL clanGUI

CXXFLAGS += -I./  -I Sources
EXTRA_LIBS=-lassimp

include ../../Makefile.conf

# EOF #

