EXAMPLE_BIN=quaternion
OBJF = ./Sources/options.o \
./Sources/shader_color.o \
./Sources/model.o \
./Sources/example.o \
./Sources/graphic_store.o \
./Sources/program.o \
./Sources/scene_object.o \
./Sources/scene.o \
./Sources/precomp.o \
../Clan3D/Collada/collada_effect_float_param.o \
../Clan3D/Collada/collada_material.o \
../Clan3D/Collada/collada.o \
../Clan3D/Collada/collada_image.o \
../Clan3D/Collada/collada_source.o \
../Clan3D/Collada/collada_input_shared.o \
../Clan3D/Collada/collada_input_unshared.o \
../Clan3D/Collada/collada_vertices.o \
../Clan3D/Collada/collada_effect_texture.o \
../Clan3D/Collada/collada_triangles.o \
../Clan3D/Collada/collada_geometry.o \
../Clan3D/Collada/collada_effect.o \
../Clan3D/Collada/collada_mesh.o \
../Clan3D/Collada/collada_effect_color_texture.o

LIBS=clanApp clanDisplay clanCore clanGL clanGUI

CXXFLAGS += -I./ -I../../Object3D/Collada -I Sources

include ../../Makefile.conf

# EOF #

