EXAMPLE_BIN=pacmanevolutions

OBJF=age_2d.o age_3d.o age_ascii.o elapsed_timer.o \
game_object_ghost.o game_object_moving.o game_object_pacman.o \
game_world.o map.o precomp.o program.o \
text_explosion_2d.o text_explosion_ascii.o

LIBS=clanCore clanDisplay clanApp clanGL clanSWRender clanSound

include ../../Makefile.conf

# EOF #
