EXAMPLE_BIN=blend
OBJF = ./Sources/options.o \
./Sources/app.o \
./Sources/program.o \
./Sources/precomp.o

LIBS=clanApp clanDisplay clanCore clanSWRender clanGL clanGL1 clanGUI

include ../../Makefile.conf

# EOF #

