EXAMPLE_BIN=blend
OBJF = ./Sources/options.o \
./Sources/app.o \
../../ThemeAero/Sources/theme.o \
./Sources/precomp.o

CXXFLAGS += -I./  -I Sources
LIBS=clanApp clanDisplay clanCore clanGL clanUI

include ../../Makefile.conf

# EOF #

