EXAMPLE_BIN=textureview
OBJF = \
./Sources/gui.o \
../../ThemeAero/Sources/theme.o \
./Sources/precomp.o

LIBS=clanApp clanDisplay clanCore clanGL clanUI

CXXFLAGS += -I./  -I Sources

include ../../Makefile.conf

# EOF #

