EXAMPLE_BIN=bumpmapping
OBJF = ./Sources/options.o \
./Sources/model.o \
./Sources/example.o \
./Sources/graphic_store.o \
./Sources/program.o \
./Sources/scene_object.o \
./Sources/scene.o \
./Sources/precomp.o \
./Sources/shader_bumpmap.o

LIBS=clanApp clanDisplay clanCore clanGL clanGUI

CXXFLAGS += -I./ -I../../Object3D/Collada -I Sources
EXTRA_LIBS=-lassimp

include ../../Makefile.conf

# EOF #

