EXAMPLE_BIN=methane
OBJF = sources/game.o sources/baddie.o sources/methane.o sources/target.o sources/maps.o sources/gfxoff.o sources/mapdata.o sources/objlist.o sources/doc.o sources/bitdraw.o sources/global.o sources/suck.o sources/power.o sources/goodie.o sources/bititem.o sources/player.o sources/weapon.o sources/bitgroup.o sources/boss.o sources/sound.o sources/gasobj.o sources/misc.o
#LIBS=clanApp clanDisplay clanCore clanGL clanSound clanMikMod
LIBS=clanApp clanDisplay clanCore clanGL
include ../Makefile.conf

# EOF #

