EXAMPLE_BIN=gui_system
OBJF =  Sources/program.o Sources/GUI.o Sources/precomp.o

LIBS=clanApp clanDisplay clanCore clanGL clanGUI clanSWRender

CXXFLAGS += -I./ -I Sources

include ../../Makefile.conf

# EOF #

