EXAMPLE_BIN=gui
OBJF = precomp.o app.o checkbox.o GUI.o info.o lineedit.o program.o pushbutton.o radiobutton.o scrollbar.o slider.o progressbar.o tabpage.o menubar.o spin.o combobox.o gui_system.o gui_texture.o manager.o listview.o
LIBS=clanApp clanDisplay clanCore clanGL clanGUI

include ../Makefile.conf

# EOF #

