EXAMPLE_BIN=mikmod
OBJF = Sources/mikmod.o Sources/module_reader.o Sources/soundprovider_mikmod.o Sources/soundprovider_mikmod_session.o Sources/precomp.o Sources/program.o

LIBS=clanApp clanSound

include ../../Makefile.conf

# EOF #

