EXAMPLE_BIN=ctalk

OBJF= \
Framework/preferences_viewer.o \
Framework/preferences_page.o \
Framework/view.o \
Framework/notification_area_icon.o \
Framework/application.o \
Framework/mainframe.o \
Framework/view_workspace.o \
Framework/ribbon.o \
Framework/crash_reporter.o \
Document/irc_text.o \
Document/irc_message.o \
Document/irc_entity.o \
Document/xml_settings.o \
Document/xml_settings_map.o \
Document/xml_settings_document.o \
Document/xml_settings_list.o \
Document/document.o \
Document/irc_connection.o \
Document/command.o \
Document/irc_session.o \
Document/irc_connection_queues.o \
precomp.o \
Views/ServerList/server_list_view.o \
Views/ServerList/server_general_page.o \
Views/Chat/channel_topic.o \
Views/Chat/chat.o \
Views/Chat/dlg_topic.o \
Views/Chat/text_edit.o \
Views/Chat/chatview.o

LIBS=clanCore clanApp clanDisplay clanGUI clanNetwork clanGDI clanRegExp

CXXFLAGS += -I./ -IFramework -IDocument -IViews

include ../Makefile.conf

# EOF #
