EXAMPLE_BIN=ctalk

OBJF=application.o chat.o chatview.o dlg_connect.o document.o ircconnection.o mainframe.o precomp.o server_list_view.o view.o

LIBS=clanCore clanApp clanDisplay clanGUI clanNetwork clanGL

include ../Makefile.conf

# EOF #
