EXAMPLE_BIN=pilotspuzzle
OBJF = Game.o \
PositionCalculator.o \
Puzzle.o \
SpriteManager.o \
main.o

LIBS=clanGUI clanApp clanCore clanGUI clanGL clanDisplay clanGUIStyleSilver

include ../Makefile.conf

# EOF #
