EXAMPLE_BIN=object3d
OBJF = ./Sources/example.o \
./Sources/program.o \
./Sources/shader.o \
./Sources/precomp.o

LIBS=clanApp clanDisplay clanCore clanGL
EXTRA_LIBS=-lassimp

CXXFLAGS += -I./ -I Sources

include ../../Makefile.conf

# EOF #

