EXAMPLE_BIN=spritesrts

OBJF=./Sources/world.o \
./Sources/app.o \
./Sources/tankvehicle.o \
./Sources/building.o \
./Sources/program.o \
./Sources/precomp.o \
./Sources/missile.o


LIBS=clanCore clanDisplay clanSound clanApp clanGL clanSWRender

include ../../Makefile.conf

# EOF #
