EXAMPLE_BIN=gui
OBJF =  Sources/checkbox.o \
 Sources/pushbutton.o \
 Sources/app.o \
 Sources/progressbar.o \
 Sources/spin.o \
 Sources/gui_texture.o \
 Sources/slider.o \
 Sources/tabpage.o \
 Sources/program.o \
 Sources/gui_system.o \
 Sources/manager.o \
 Sources/GUI.o \
 Sources/scrollbar.o \
 Sources/listview.o \
 Sources/menubar.o \
 Sources/lineedit.o \
 Sources/precomp.o \
 Sources/combobox.o \
 Sources/radiobutton.o \
 Sources/info.o

LIBS=clanApp clanDisplay clanCore clanGL clanGUI

include ../../Makefile.conf

# EOF #

