EXAMPLE_BIN=gui
OBJF =  Sources/app.o \
 Sources/game_component.o \
 Sources/toolbar.o \
 Sources/program.o \
 Sources/radial_menu.o \
 Sources/precomp.o


LIBS=clanApp clanDisplay clanCore clanSWRender clanGL clanGL1 clanGUI

include ../../Makefile.conf

# EOF #

