EXAMPLE_BIN=displaytarget
OBJF = Sources/target.o \
 Sources/program.o \
 Sources/precomp.o

LIBS=clanApp clanDisplay clanCore clanGL clanGL1 clanSWRender clanGUI

include ../../Makefile.conf

# EOF #

