EXAMPLE_BIN=gui_layered
OBJF =  ../CommonCode/Sources/checkbox.o \
 ../CommonCode/Sources/pushbutton.o \
 ../CommonCode/Sources/balls.o \
 Sources/app.o \
 Sources/gui_3d.o \
 ../CommonCode/Sources/progressbar.o \
 ../CommonCode/Sources/spin.o \
 Sources/gui_layered.o \
 ../CommonCode/Sources/slider.o \
 ../CommonCode/Sources/tabpage.o \
 Sources/program.o \
 ../CommonCode/Sources/theme.o \
 Sources/GUI.o \
 Sources/panel3d.o \
 ../CommonCode/Sources/scrollbar.o \
 ../CommonCode/Sources/listview.o \
 ../CommonCode/Sources/menubar.o \
 ../CommonCode/Sources/lineedit.o \
 Sources/precomp.o \
 ../CommonCode/Sources/combobox.o \
 ../CommonCode/Sources/radiobutton.o \
 ../CommonCode/Sources/info.o

LIBS=clanApp clanDisplay clanCore clanGL clanGUI

CXXFLAGS += -I./ -I../../CommonCode/Sources -I Sources

include ../../Makefile.conf

# EOF #

