EXAMPLE_BIN=stencil
OBJF = Sources/app.o Sources/program.o Sources/options.o
LIBS=clanApp clanDisplay clanCore clanGL clanGUI
CXXFLAGS += -I Sources -I ./

include ../../Examples/Makefile.conf

# EOF #

