EXAMPLE_BIN=gui3d
OBJF = Sources/app.o Sources/component3d.o Sources/gui.o Sources/panel.o Sources/program.o Sources/slider.o Sources/window_1.o
LIBS=clanApp clanDisplay clanCore clanGL clanGUI

include ../Makefile.conf

# EOF #

