EXAMPLE_BIN=scroller
OBJF = Sources/scroller.o Sources/precomp.o Sources/program.o Sources/text.o
#LIBS=clanApp clanDisplay clanCore clanGL
#LIBS=clanApp clanDisplay clanCore clanGL1
LIBS=clanApp clanDisplay clanCore clanSWRender

include ../../Makefile.conf

# EOF #

