EXAMPLE_BIN=gui_direct
OBJF =  Sources/app.o Sources/program.o  Sources/precomp.o ../CommonCode/Sources/balls.o

LIBS=clanApp clanDisplay clanCore clanGL clanGUI clanSWRender

CXXFLAGS += -I./ -I Sources -I ../CommonCode/Sources/

include ../../Makefile.conf

# EOF #

