EXAMPLE_BIN=gui_direct
OBJF =  Sources/app.o Sources/balls.o Sources/program.o  Sources/precomp.o

LIBS=clanApp clanDisplay clanCore clanGL clanGUI clanSWRender

CXXFLAGS += -I./ -I Sources

include ../../Makefile.conf

# EOF #

