EXAMPLE_BIN=test
OBJF = test.o test_cl_endian.o test_path_help.o test_file_help.o test_datatypes.o test_directory_scanner.o test_iodevice_memory.o test_iodevice.o test_virtual_directory.o test_vfs.o
LIBS=clanApp clanCore

include ../../../Examples/Makefile.conf

# EOF #

