EXAMPLE_BIN=spritesrts

OBJF=\
	Sources/app.o \
	Sources/building.o \
	Sources/missile.o \
	Sources/tankvehicle.o \
	Sources/world.o

LIBS=clanCore clanDisplay clanSound clanApp clanGL

include ../Makefile.conf

# EOF #
