EXAMPLE_BIN=pixelbuffer
OBJF = ./Sources/app.o \
./Sources/program.o \
./Sources/precomp.o

LIBS=clanApp clanDisplay clanCore clanGL clanGUI
CXXFLAGS += -I Sources -I ./

include ../../Makefile.conf

# EOF #

