EXAMPLE_BIN=test
OBJF = test.o test_sha1.o test_sha224.o test_sha256.o test_sha384.o test_sha512.o test_sha512_224.o test_sha512_256.o test_aes128.o test_aes192.o test_aes256.o test_md5.o test_rsa.o
LIBS=clanApp clanCore

include ../../../Examples/Makefile.conf

# EOF #

