EXAMPLE_BIN=colorwheel
OBJF = Sources/app.o Sources/program.o Sources/colorwheel.o
LIBS=clanApp clanDisplay clanCore clanGL clanGUI
CXXFLAGS += -I Sources -I./

include ../../Examples/Makefile.conf

# EOF #

