EXAMPLE_BIN=geometryshader
OBJF = ./Sources/particle_object.o \
./Sources/example.o \
./Sources/graphic_store.o \
./Sources/program.o \
./Sources/scene_object.o \
./Sources/shader_color_geometry.o \
./Sources/scene.o \
./Sources/precomp.o

LIBS=clanApp clanDisplay clanCore clanGL

CXXFLAGS += -I./ -I Sources

include ../../Makefile.conf

# EOF #

