EXAMPLE_BIN=collision
OBJF = Sources/precomp.o \
Sources/CollisionLIB/outline_provider_file_impl.o \
Sources/CollisionLIB/outline_provider_bitmap.o \
Sources/CollisionLIB/contour.o \
Sources/CollisionLIB/outline_provider_bitmap_impl.o \
Sources/CollisionLIB/collision_outline.o \
Sources/CollisionLIB/outline_provider_file.o \
Sources/CollisionLIB/outline_math.o \
Sources/CollisionLIB/collision_outline_impl.o \
Sources/collision.o

LIBS=clanApp clanCore clanDisplay clanGL clanXML clanSound

include ../../../Examples/Makefile.conf

CXXFLAGS += -ISources

# EOF #

