EXAMPLE_BIN=ReferenceDocs
OBJF = reference_docs.o reference_all_classes.o reference_class.o reference_define.o reference_enum.o reference_function.o reference_grouped_classes.o reference_index.o reference_typedef.o
LIBS=clanCore
EXTRA_LIBS=-lpthread

include ../../../Examples/Makefile.conf

# EOF #

