EXAMPLE_BIN=guieditor
OBJF = application.o dialog_document.o component_type.o grid_component.o  precomp.o selection.o system_dialog.o view_border.o holder_component.o property_component.o  main.o  custom_component.o main_window.o dialog_container.o dialog_component.o source_generator_dialog.o callback_data.o callback_info.o

LIBS=clanApp clanDisplay clanCore clanGL clanGUI

EXTRA_LIBS=-L/usr/share/qt3/lib -lqt-mt

include ../../Examples/Makefile.conf

# EOF #

