EXAMPLE_BIN=guieditor
OBJF = \
./Sources/ComponentTypes/PropertyItems/Popups/anchor_popup.o \
./Sources/ComponentTypes/PropertyItems/Popups/line_edit_popup.o \
./Sources/ComponentTypes/component_types.o \
./Sources/ComponentTypes/custom_component.o \
./Sources/PropertyComponent/property_component.o \
./Sources/PropertyComponent/property_item_popup.o \
./Sources/PropertyComponent/EditState/property_component_edit_state.o \
./Sources/PropertyComponent/EditState/property_component_edit_state_revert_button.o \
./Sources/PropertyComponent/EditState/property_component_edit_state_none.o \
./Sources/PropertyComponent/EditState/property_component_edit_state_header_sizing.o \
./Sources/PropertyComponent/EditState/property_component_edit_state_node_opener.o \
./Sources/Selection/selection.o \
./Sources/GridComponent/grid_object.o \
./Sources/GridComponent/grid_component.o \
./Sources/GridComponent/snapline.o \
./Sources/GridComponent/EditState/grid_edit_state_boundary_sizing.o \
./Sources/GridComponent/EditState/grid_edit_state.o \
./Sources/GridComponent/EditState/grid_edit_state_create_tool.o \
./Sources/GridComponent/EditState/grid_edit_state_net_selecting.o \
./Sources/GridComponent/EditState/grid_edit_state_object_moving.o \
./Sources/GridComponent/EditState/grid_edit_state_object_sizing.o \
./Sources/GridComponent/EditState/grid_edit_state_none.o \
./Sources/MainWindow/view_border.o \
./Sources/MainWindow/gui_editor_window.o \
./Sources/MainWindow/edit_columns_window.o \
./Sources/precomp.o \
./Sources/application.o \
./Sources/main.o

LIBS=clanApp clanDisplay clanCore clanSWRender clanGUI

#EXTRA_LIBS=-L/usr/share/qt3/lib -lqt-mt
CXXFLAGS += -I./ -I Sources -I Sources/ComponentTypes -I Sources/GridComponent -I Sources/MainWindow -I Sources/PropertyComponent -I Sources/Selection

include ../../Examples/Makefile.conf

# EOF #

