EXAMPLE_BIN=object3d
OBJF = ./example.o \
./precomp.o \
./Collada/collada_source.o \
./Collada/collada_mesh.o \
./Collada/collada_vertices.o \
./Collada/collada_effect_color_texture.o \
./Collada/collada_triangles.o \
./Collada/collada_image.o \
./Collada/collada_effect.o \
./Collada/collada_effect_float_param.o \
./Collada/collada_effect_texture.o \
./Collada/collada_input_shared.o \
./Collada/collada.o \
./Collada/collada_material.o \
./Collada/collada_input_unshared.o \
./Collada/collada_geometry.o

LIBS=clanApp clanDisplay clanCore clanGL1

CXXFLAGS += -I./ -ICollada

include ../Makefile.conf

# EOF #

