EXAMPLE_BIN=tilemap
OBJF = Sources/game.o Sources/precomp.o Sources/program.o Sources/tilemap.o
#LIBS=clanApp clanDisplay clanCore clanGL
#LIBS=clanApp clanDisplay clanCore clanGL1
LIBS=clanApp clanDisplay clanCore clanSWRender

include ../../Makefile.conf

# EOF #

