EXAMPLE_BIN=pacman

OBJF=./sources/world.o \
./sources/map.o \
./sources/gameobject_ghost.o \
./sources/gameobject_pacman.o \
./sources/application.o \
./sources/program.o \
./sources/gameobject_moving.o \
./sources/fontblowup.o \
./sources/precomp.o

LIBS=clanCore clanDisplay clanApp clanGL clanSWRender

include ../../Makefile.conf

# EOF #
