EXAMPLE_BIN=vertexbuffer
OBJF = ./Sources/app.o \
./Sources/precomp.o \
./Sources/shader.o

LIBS=clanApp clanDisplay clanCore clanGL
CXXFLAGS += -I Sources -I./

include ../../Makefile.conf

# EOF #

