EXAMPLE_BIN=stencil
OBJF = ./Sources/options.o \
./Sources/app.o \
./Sources/program.o \
./Sources/precomp.o

LIBS=clanApp clanDisplay clanCore clanSWRender clanGL clanGL1 clanGUI
CXXFLAGS += -I Sources -I ./

include ../../Makefile.conf

# EOF #

