EXAMPLE_BIN=guitexturedbuttons
OBJF =  Sources/program.o \
 Sources/gui.o \
 Sources/precomp.o

LIBS=clanApp clanDisplay clanCore clanSWRender clanGUI clanGL

include ../../Makefile.conf

# EOF #

