EXAMPLE_BIN=mapmode
OBJF = ./Sources/options.o \
./Sources/app.o \
./Sources/program.o \
./Sources/precomp.o

LIBS=clanApp clanDisplay clanCore clanGL clanGUI clanSWRender
CXXFLAGS += -I Sources -I ./

include ../../Makefile.conf

# EOF #

