EXAMPLE_BIN=mapmode
OBJF = ./Sources/options.o \
./Sources/app.o \
./Sources/theme.o \
./Sources/precomp.o

LIBS=clanApp clanDisplay clanCore clanGL clanUI
CXXFLAGS += -I Sources -I ./

include ../../Makefile.conf

# EOF #

