EXAMPLE_BIN=charactercontroller
SOURCE = $(wildcard *.cpp)
OBJF = $(patsubst %.cpp,%.o,$(SOURCE))

LIBS=clanApp clanDisplay clanCore clanGL clanGUI clanSWRender clanPhysics3D clanScene3D 

include ../../Makefile.conf

# EOF #

