EXAMPLE_BIN=test
OBJF = test.o test_vector.o test_matrix.o test_line.o test_line_ray.o test_line_segment.o test_triangle.o test_angle.o test_quaternion.o test_bigint.o
LIBS=clanApp clanCore

include ../../../Examples/Makefile.conf

# EOF #

