EXAMPLE_BIN=css_editor
OBJF = Sources/precomp.o Sources/app.o Sources/option_value.o Sources/option_list.o Sources/option_rgb.o Sources/program.o Sources/options.o
LIBS=clanApp clanDisplay clanCore clanGL clanSWRender clanGUI clanCSSLayout 

include ../../Makefile.conf

# EOF #

