EXAMPLE_BIN=direct_render
OBJF = ./Sources/app.o \
./Sources/gui_window_manager_direct.o \
./Sources/gui_window_manager_direct_window.o \
./Sources/gui_window_manager_provider_direct.o \
./Sources/options.o \
./Sources/precomp.o \
./Sources/program.o

LIBS=clanApp clanDisplay clanCore clanGL1 clanGUI

include ../../Makefile.conf

# EOF #

