EXAMPLE_BIN=chess3d
OBJF = ./Sources/model.o \
./Sources/3D/position.o \
./Sources/3D/camera.o \
./Sources/3D/lib3ds_help.o \
./Sources/3D/orientation.o \
./Sources/skybox.o \
./Sources/program.o \
./Sources/chess.o \
./Sources/precomp.o


LIBS=clanApp clanDisplay clanCore clanGL
EXTRA_LIBS=-l3ds

CXXFLAGS += -I./ -I3D

include ../../Makefile.conf

# EOF #

