EXAMPLE_BIN=svgviewer
OBJF = \
./Sources/svg_element_visitor.o \
./Sources/precomp.o \
./Sources/svg_renderer.o \
./Sources/svg.o \
./Sources/svg_tree.o \
./Sources/svg_viewer.o \
./Sources/svg_attribute_reader.o \
./Sources/svg_transform_scope.o

LIBS=clanApp clanDisplay clanCore clanGL clanXML clanSound

include ../../Makefile.conf

# EOF #

