EXAMPLE_BIN=water
OBJF = ./Sources/model.o \
./Sources/example.o \
./Sources/shader_texture.o \
./Sources/graphic_store.o \
./Sources/program.o \
./Sources/scene_object.o \
./Sources/scene.o \
./Sources/precomp.o

LIBS=clanApp clanDisplay clanCore clanGL
EXTRA_LIBS=-lassimp

CXXFLAGS += -I./  -I Sources

include ../../Makefile.conf

# EOF #

