EXAMPLE_BIN=colorwheel
OBJF = ./Sources/colorwheel.o \
./Sources/app.o \
./Sources/precomp.o

LIBS=clanApp clanDisplay clanCore clanGL clanGUI
CXXFLAGS += -I Sources -I./

include ../../Makefile.conf

# EOF #

